name: flutter_cursor_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.3
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Navigation
  get: ^4.6.6
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
