// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJdKT5yZ5pMciz0L1WO_VlzG715Ji2pE',
    appId: '1:809389517578:web:8016a771dac463b4aca8f3',
    messagingSenderId: '809389517578',
    projectId: 'tailorapp-5fa6a',
    authDomain: 'tailorapp-5fa6a.firebaseapp.com',
    storageBucket: 'tailorapp-5fa6a.firebasestorage.app',
    measurementId: 'G-W50YVSRS38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGiCQKUV3r6AidNTzgmGkQtOeaDuVOqVw',
    appId: '1:809389517578:android:452004681fce1e1eaca8f3',
    messagingSenderId: '809389517578',
    projectId: 'tailorapp-5fa6a',
    storageBucket: 'tailorapp-5fa6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWlqmhximYC4Uc9lZDCV0JwNII9DzrAE',
    appId: '1:809389517578:ios:fbaa88ea3c811fa4aca8f3',
    messagingSenderId: '809389517578',
    projectId: 'tailorapp-5fa6a',
    storageBucket: 'tailorapp-5fa6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCursorApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlWlqmhximYC4Uc9lZDCV0JwNII9DzrAE',
    appId: '1:809389517578:ios:fbaa88ea3c811fa4aca8f3',
    messagingSenderId: '809389517578',
    projectId: 'tailorapp-5fa6a',
    storageBucket: 'tailorapp-5fa6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCursorApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVJdKT5yZ5pMciz0L1WO_VlzG715Ji2pE',
    appId: '1:809389517578:web:a00865c5abb153d6aca8f3',
    messagingSenderId: '809389517578',
    projectId: 'tailorapp-5fa6a',
    authDomain: 'tailorapp-5fa6a.firebaseapp.com',
    storageBucket: 'tailorapp-5fa6a.firebasestorage.app',
    measurementId: 'G-SFTJ3Z2FPZ',
  );
}
